# Generated by Django 5.1.7 on 2025-04-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras_app', '0001_initial'),
        ('insumos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumo'),
        ),
    ]
