# Generated by Django 5.1.7 on 2025-04-04 04:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_insumos_app', '0002_inventarioinsumos_activo'),
        ('producciones_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_merma', models.TextField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_insumos_app.inventarioinsumos')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producciones_app.produccion')),
            ],
        ),
    ]
