# Generated by Django 5.1.7 on 2025-04-03 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas_app', '0002_galleta_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_preparacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galletas_app.galleta')),
            ],
        ),
    ]
