# Generated by Django 5.1.7 on 2025-04-08 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas_app', '0002_galleta_medida'),
        ('producciones_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galletas_app.galleta')),
            ],
        ),
    ]
