# Generated by Django 5.1.7 on 2025-04-04 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producciones_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioGalletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_galleta', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_caducidad', models.DateTimeField(default=django.utils.timezone.now)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producciones_app.produccion')),
            ],
        ),
    ]
