# Generated by Django 4.2.18 on 2025-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('telefono', models.TextField(max_length=15)),
                ('direccion', models.TextField(max_length=200)),
            ],
        ),
    ]
