# Generated by Django 4.2.20 on 2025-04-03 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galletas_app', '0001_initial'),
        ('insumos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('para_produccion', models.BooleanField(default=False)),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galletas_app.galleta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('merma', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
            ],
        ),
    ]
