# Generated by Django 5.1.5 on 2025-03-22 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen_app', '0002_galleta_inventariogalleta_inventarioinsumo_merma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.insumo')),
            ],
            options={
                'verbose_name': 'Detalle Receta',
                'verbose_name_plural': 'Detalles Receta',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ingredientes', models.ManyToManyField(through='recetas_app.DetalleReceta', to='almacen_app.insumo')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta'),
        ),
    ]
