# Generated by Django 5.1.7 on 2025-04-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereceta',
            name='merma',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
