# Generated by Django 5.1.7 on 2025-04-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('cantidad_minima', models.IntegerField(default=0)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidas_app.medida')),
            ],
        ),
    ]
