# Generated by Django 5.1.7 on 2025-04-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
