# Generated by Django 5.1.7 on 2025-04-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_existente', models.IntegerField()),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras_app.detallecompra')),
            ],
        ),
    ]
