# Generated by Django 5.1.7 on 2025-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_insumos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioinsumos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
