# Generated by Django 5.1.5 on 2025-03-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Galleta',
                'verbose_name_plural': 'Galletas',
            },
        ),
        migrations.CreateModel(
            name='InventarioGalleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_caducidad', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cantidad_minima', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_caducidad', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
