# Generated by Django 5.1.5 on 2025-03-22 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0002_galleta_inventariogalleta_inventarioinsumo_merma'),
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta'),
        ),
        migrations.AddField(
            model_name='inventariogalleta',
            name='galleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.galleta'),
        ),
        migrations.AddField(
            model_name='inventarioinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.insumo'),
        ),
        migrations.AddField(
            model_name='merma',
            name='galleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen_app.galleta'),
        ),
        migrations.AddField(
            model_name='merma',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen_app.insumo'),
        ),
    ]
