# Generated by Django 5.1.7 on 2025-04-03 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas_app', '0001_initial'),
        ('medidas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medidas_app.medida'),
            preserve_default=False,
        ),
    ]
