# Generated by Django 5.1.7 on 2025-04-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galletas_app', '0002_galleta_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='precio_produccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
